from __future__ import annotations
import json,os,subprocess,sys,time
from datetime import datetime,timezone
from pathlib import Path
REPO=Path(r'C:\Users\aaron\Desktop\URAP');RUN=REPO/'artifacts'/'detached_action_chunk_neighbor_iou_v47';PROGRESS=RUN/'progress.json';OUT=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_iou_v47');DATA=Path(r'D:\URAP_vatd_rank_results\action_chunk_full_dev_v36');N=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_v44');PREREQ=Path(r'D:\URAP_vatd_rank_results\action_chunk_graph_v43\official_summary.json')
def report(stage,done,**extra):RUN.mkdir(parents=True,exist_ok=True);payload={'stage':stage,'done':done,'total':3,'updated':datetime.now(timezone.utc).astimezone().isoformat(),**extra};PROGRESS.write_text(json.dumps(payload,indent=2),encoding='utf8');print(json.dumps(payload),flush=True)
def execute(stage,done,cmd):
 p=subprocess.Popen(cmd,cwd=REPO,env={**os.environ,'PYTHONPATH':str(REPO)+os.pathsep+str(REPO/'tools'),'PYTHONUNBUFFERED':'1'});report(stage,done,child_pid=p.pid,command=cmd);code=p.wait()
 if code:raise subprocess.CalledProcessError(code,cmd)
def main():
 OUT.mkdir(parents=True,exist_ok=True)
 while not PREREQ.is_file():report('waiting_for_graph_audit',0,prerequisite=str(PREREQ));time.sleep(30)
 execute('train_neighbor_iou',0,[sys.executable,str(REPO/'tools'/'train_action_chunk_neighbor_regression.py'),'--train-pkl',r'D:\URAP_nps_train_tvd\runs\nps_train_rank_source\predictionsgt\predictionsgt_split_0.pkl','--train-forward',str(DATA/'train_forward.jsonl'),'--train-backward',str(DATA/'train_backward.jsonl'),'--train-neighbor',str(N/'train_neighbor_scores.jsonl'),'--val-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--val-forward',str(DATA/'val_forward.jsonl'),'--val-backward',str(DATA/'val_backward.jsonl'),'--val-neighbor',str(N/'val_neighbor_scores.jsonl'),'--test-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--test-forward',str(DATA/'test_forward.jsonl'),'--test-backward',str(DATA/'test_backward.jsonl'),'--test-neighbor',str(N/'test_neighbor_scores.jsonl'),'--out-val-scores',str(OUT/'val_oof_scores.jsonl'),'--out-test-scores',str(OUT/'test_scores.jsonl'),'--out-model-dir',str(OUT/'models'),'--out-summary',str(OUT/'train_summary.json')]);execute('select_fusion_on_oof',1,[sys.executable,str(REPO/'tools'/'sweep_tvd_predictionsgt_score_fusion.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--tracklet-jsonl',str(OUT/'val_oof_scores.jsonl'),'--per-row-score','--score-field','action_chunk_neighbor_iou_score','--modes','geom-mix','--alphas','.02,.04,.06,.08,.1,.14,.2,.3,.4,.55,.7','--out-json',str(OUT/'val_sweep.json')]);validation=json.loads((OUT/'val_sweep.json').read_text(encoding='utf8'))['best'];execute('fixed_test',2,[sys.executable,str(REPO/'tools'/'sweep_tvd_predictionsgt_score_fusion.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--tracklet-jsonl',str(OUT/'test_scores.jsonl'),'--per-row-score','--score-field','action_chunk_neighbor_iou_score','--modes','geom-mix','--alphas',str(validation['alpha']),'--out-json',str(OUT/'test_fixed.json')]);test=json.loads((OUT/'test_fixed.json').read_text(encoding='utf8'))['best'];summary={'protocol':'pure Action Chunk continuous-IoU target; strict OOF fusion; fixed test','validation_selection':validation,'test_fixed':test,'target_map50':.97,'target_met':test['map50']>=.97};(OUT/'official_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8');report('done',3,summary=summary);return 0
if __name__=='__main__':raise SystemExit(main())
