from __future__ import annotations
import json,os,subprocess,sys,time
from datetime import datetime
from pathlib import Path
REPO=Path(r"C:\Users\aaron\Desktop\URAP");RUN=REPO/"artifacts"/"detached_ard100_yolomg_vatd_v2";PROGRESS=RUN/"progress.json";OUT=Path(r"D:\URAP_vatd_rank_results\ard100_yolomg_generalization_v2");PKL=OUT/"ard100_yolomg_predictionsgt.pkl";BASELINE=OUT/"detector_baseline.json";ACTION=OUT/"action_bank_summary.json";FR=Path(r"D:\URAP_datasets\TransVisDrone\ARD100\AllFrames\test");W=REPO/"artifacts"/"ego_adaptive_vatd"/"nps_train_full_u_epoch1_noshuffle_20260606"/"ego_adaptive_vatd.pt";RR=OUT/"vatd_route";TD=OUT/"vatd_tracklets";T=TD/"proposal_tracklets.jsonl";S=OUT/"vatd_scores.jsonl";A=OUT/"vatd_attached.jsonl"
def report(stage,done,**extra):RUN.mkdir(parents=True,exist_ok=True);payload={"stage":stage,"done":done,"total":6,"updated":datetime.now().astimezone().isoformat(),**extra};PROGRESS.write_text(json.dumps(payload,indent=2),encoding="utf8");print(json.dumps(payload),flush=True)
def execute(stage,done,cmd):
 p=subprocess.Popen(cmd,cwd=REPO,env={**os.environ,"PYTHONUNBUFFERED":"1","PYTHONPATH":str(REPO)});report(stage,done,child_pid=p.pid,command=cmd);code=p.wait()
 if code:raise RuntimeError(f"{stage} failed {code}")
def main():
 while not PKL.is_file():report("waiting_for_predictions",0);time.sleep(30)
 execute("export_route_b",1,[sys.executable,str(REPO/"tools"/"export_tvd_predictionsgt_to_route_b.py"),"--predictionsgt-pkl",str(PKL),"--out-run-root",str(RR/"run_root"),"--out-gt-csv",str(RR/"gt.csv"),"--out-summary",str(RR/"summary.json"),"--frame-root",str(FR),"--image-width","1920","--image-height","1080"]);execute("build_tracklets",2,[sys.executable,"-m","qstr_dronedet.cli","build-proposal-tracklet-dataset","--run-roots",str(RR/"run_root"),"--gt-csv",str(RR/"gt.csv"),"--out",str(TD),"--profile","hard_recovery","--diagnostics-name","diagnostics_raw.jsonl","--max-gap","3","--base-radius","18","--radius-per-side",".75","--min-iou",".05","--min-score","0","--min-tracklet-rows","3","--iou-threshold",".5","--center-threshold","24","--hard-tiny-side","24","--hard-low-score",".25"]);
 while not ACTION.is_file():report("waiting_for_action_bank_before_gpu_vatd",3);time.sleep(30)
 execute("score_frozen_vatd",3,[sys.executable,"-m","qstr_dronedet.cli","score-ego-adaptive-vatd-tracklets","--tracklet-jsonl",str(T),"--weights",str(W),"--out",str(S),"--frame-root",str(FR),"--image-name-template","{seq}_{frame_id_05d}.jpg","--error-scale",".02","--min-tracklet-rows","9","--batch-size","512","--num-workers","0","--frame-cache-size","256","--fusion-mode","motion_action"]);execute("attach_scores",4,[sys.executable,"-m","qstr_dronedet.cli","attach-vatd-scores-to-tracklets","--tracklet-jsonl",str(T),"--vatd-scores",str(S),"--out",str(A)]);execute("evaluate_fixed_vatd",5,[sys.executable,str(REPO/"tools"/"sweep_tvd_predictionsgt_action_rescore.py"),"--tvd-root",r"D:\urap_modal_stage\TransVisDrone","--predictionsgt-pkl",str(PKL),"--tracklet-jsonl",str(A),"--score-field","vatd_score","--centers",".01","--betas",".02","--modes","boost-only","--missing-score-behaviors","keep","--out-json",str(OUT/"vatd_fixed.json")]);base=json.loads(BASELINE.read_text());vatd=json.loads((OUT/"vatd_fixed.json").read_text())["best"];action=json.loads(ACTION.read_text())["action_bank"];summary={"protocol":"same ARD100 YOLOMG candidates; frozen NPS VATD vs frozen NPS Action Bank","detector":base,"vatd":vatd,"action_bank":action,"action_over_vatd_points":100*(action["map50"]-vatd["map50"]),"target_3pt_met":action["map50"]-vatd["map50"]>=.03};(OUT/"official_comparison.json").write_text(json.dumps(summary,indent=2));report("done",6,summary=summary);return 0
if __name__=="__main__":raise SystemExit(main())
