from __future__ import annotations
import json,os,subprocess,sys
from datetime import datetime
from pathlib import Path
R=Path(r'C:\Users\aaron\Desktop\URAP');RUN=R/'artifacts'/'detached_tvd_resolution_specialist_v94';P=RUN/'progress.json';O=Path(r'D:\URAP_vatd_rank_results\tvd_resolution_specialist_v94');D=Path(r'D:\URAP_vatd_rank_results\action_chunk_full_dev_v36');N=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_v44');TRAIN=Path(r'D:\URAP_nps_train_tvd\runs\nps_train_rank_source\predictionsgt\predictionsgt_split_0_fixed_canvas.pkl');TEST=Path(r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl');S=R/'data_templates'/'nps_sequence_sizes.json'
def rep(stage,done,**extra):RUN.mkdir(parents=True,exist_ok=True);P.write_text(json.dumps({'stage':stage,'done':done,'total':3,'updated':datetime.now().astimezone().isoformat(),**extra},indent=2),encoding='utf8');print(stage,flush=True)
def go(stage,done,command):
 process=subprocess.Popen(command,cwd=R,env={**os.environ,'PYTHONPATH':str(R),'PYTHONUNBUFFERED':'1'});rep(stage,done,child_pid=process.pid,command=command);code=process.wait()
 if code:raise RuntimeError(f'{stage} failed {code}')
def main():
 O.mkdir(parents=True,exist_ok=True);go('train_1920_specialist',0,[sys.executable,str(R/'tools'/'train_action_chunk_resolution_1920.py'),'--train-pkl',str(TRAIN),'--train-forward',str(D/'train_forward.jsonl'),'--train-backward',str(D/'train_backward.jsonl'),'--train-neighbor',str(N/'train_neighbor_scores.jsonl'),'--test-pkl',str(TEST),'--test-forward',str(D/'test_forward.jsonl'),'--test-backward',str(D/'test_backward.jsonl'),'--test-neighbor',str(N/'test_neighbor_scores.jsonl'),'--sequence-size-json',str(S),'--out-oof-pkl',str(O/'train_1920_oof.pkl'),'--out-oof-scores',str(O/'train_1920_oof_scores.jsonl'),'--out-test-scores',str(O/'test_scores.jsonl'),'--out-model-dir',str(O/'models'),'--out-summary',str(O/'train_summary.json')]);go('select_1920_oof_fusion',1,[sys.executable,str(R/'tools'/'sweep_tvd_predictionsgt_score_fusion.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',str(O/'train_1920_oof.pkl'),'--tracklet-jsonl',str(O/'train_1920_oof_scores.jsonl'),'--per-row-score','--score-field','action_chunk_1920_score','--modes','geom-mix','logit-mix','fp-suppress','replace','--alphas','.02,.04,.06,.08,.1,.14,.2,.3,.4,.55,.7','--out-json',str(O/'oof_sweep.json')]);best=json.loads((O/'oof_sweep.json').read_text(encoding='utf8'))['best'];summary={'protocol':'1920 specialist trained with corrected labels; sequence-level OOF selection; test labels untouched','oof_best':best};(O/'official_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8');rep('done',3,summary=summary);return 0
if __name__=='__main__':raise SystemExit(main())
