from __future__ import annotations
import json,os,subprocess,sys
from datetime import datetime
from pathlib import Path
REPO=Path(r'C:\Users\aaron\Desktop\URAP');RUN=REPO/'artifacts'/'detached_action_chunk_future_reliability_v77';PROGRESS=RUN/'progress.json';OUT=Path(r'D:\URAP_vatd_rank_results\action_chunk_future_reliability_v77');DATA=Path(r'D:\URAP_vatd_rank_results\action_chunk_chain_features_v75');V46=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_model_v46');FPS=REPO/'data_templates'/'nps_sequence_fps.json';FIELD='action_chunk_future_reliability'
def report(stage,done,total=3,**extra):RUN.mkdir(parents=True,exist_ok=True);payload={'stage':stage,'done':done,'total':total,'updated':datetime.now().astimezone().isoformat(),**extra};PROGRESS.write_text(json.dumps(payload),encoding='utf8');print(json.dumps(payload),flush=True)
def execute(stage,done,command):
 process=subprocess.Popen(command,cwd=REPO,env={**os.environ,'PYTHONPATH':str(REPO)+os.pathsep+str(REPO/'tools'),'PYTHONUNBUFFERED':'1'});report(stage,done,child_pid=process.pid,command=command);code=process.wait()
 if code:raise RuntimeError(f'{stage} failed with {code}')
def main():
 OUT.mkdir(parents=True,exist_ok=True);execute('train_future_reliability_gpu',0,[sys.executable,str(REPO/'tools'/'train_action_chunk_future_reliability.py'),'--train-pkl',r'D:\URAP_nps_train_tvd\runs\nps_train_rank_source\predictionsgt\predictionsgt_split_0.pkl','--train-chain',str(DATA/'train_chain.jsonl'),'--val-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--val-chain',str(DATA/'val_chain.jsonl'),'--test-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--test-chain',str(DATA/'test_chain.jsonl'),'--fps-json',str(FPS),'--out-val-scores',str(OUT/'val_oof_scores.jsonl'),'--out-test-scores',str(OUT/'test_scores.jsonl'),'--out-model-dir',str(OUT/'models'),'--out-summary',str(OUT/'train_summary.json')]);weights='0 .005 .01 .02 .04 .06 .08 .1 .14 .2 .3 .4';execute('select_oof_fusion',1,[sys.executable,str(REPO/'tools'/'sweep_action_chunk_two_row_ensemble.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--score-a',str(V46/'val_oof_scores.jsonl'),'--field-a','action_chunk_neighbor_score','--score-b',str(OUT/'val_oof_scores.jsonl'),'--field-b',FIELD,'--alphas',weights,'--betas',weights,'--out-json',str(OUT/'val_sweep.json')]);selection=json.loads((OUT/'val_sweep.json').read_text(encoding='utf8'))['best'];execute('fixed_test',2,[sys.executable,str(REPO/'tools'/'sweep_action_chunk_two_row_ensemble.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--score-a',str(V46/'test_scores.jsonl'),'--field-a','action_chunk_neighbor_score','--score-b',str(OUT/'test_scores.jsonl'),'--field-b',FIELD,'--alphas',str(selection['alpha']),'--betas',str(selection['beta']),'--out-json',str(OUT/'test_fixed.json')]);test=json.loads((OUT/'test_fixed.json').read_text(encoding='utf8'))['best'];summary={'protocol':'pure Action Chunk future-chain reliability; future 1s labels only at training; past-only inference; GPU XGBoost; held-sequence OOF selection; fixed test','validation_selection':selection,'test_fixed':test,'target_map50':.97,'target_met':test['map50']>=.97};(OUT/'official_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8');report('done',3,summary=summary);return 0
if __name__=='__main__':raise SystemExit(main())
