from __future__ import annotations
import json,os,subprocess,sys,time
from datetime import datetime
from pathlib import Path
REPO=Path(r"C:\Users\aaron\Desktop\URAP");RUN=REPO/"artifacts"/"detached_ard100_yolomg_action_bank_v2";PROGRESS=RUN/"progress.json";OUT=Path(r"D:\URAP_vatd_rank_results\ard100_yolomg_generalization_v2");PKL=OUT/"ard100_yolomg_predictionsgt.pkl";BASELINE=OUT/"detector_baseline.json";H=Path(r"D:\URAP_vatd_rank_results\ard100_generalization_v1\ard100_test_homographies.pkl");FR=Path(r"D:\URAP_datasets\TransVisDrone\ARD100\AllFrames\test");FPS=REPO/"data_templates"/"ard100_sequence_fps.json";CFG=Path(r"D:\URAP_vatd_rank_results\action_chunk_temporal_gate_v53\val_sweep.json");BM=Path(r"D:\URAP_vatd_rank_results\action_chunk_neighbor_model_v46\models");EM=Path(r"D:\URAP_vatd_rank_results\action_chunk_multi_expert_v52\models")
def report(stage,done,**extra):RUN.mkdir(parents=True,exist_ok=True);payload={"stage":stage,"done":done,"total":6,"updated":datetime.now().astimezone().isoformat(),**extra};PROGRESS.write_text(json.dumps(payload,indent=2),encoding="utf8");print(json.dumps(payload),flush=True)
def execute(stage,done,cmd):
 p=subprocess.Popen(cmd,cwd=REPO,env={**os.environ,"PYTHONUNBUFFERED":"1","PYTHONPATH":str(REPO)});report(stage,done,child_pid=p.pid,command=cmd);code=p.wait()
 if code:raise RuntimeError(f"{stage} failed {code}")
def main():
 while not (PKL.is_file() and BASELINE.is_file() and H.is_file()):report("waiting_for_predictions_and_homography",0,pkl=PKL.exists(),baseline=BASELINE.exists(),homography=H.exists());time.sleep(30)
 f=OUT/"forward_features.jsonl";b=OUT/"backward_features.jsonl";n=OUT/"neighbor_features.jsonl";bs=OUT/"v46_scores.jsonl";es=OUT/"v52_scores.jsonl";common=[sys.executable,str(REPO/"tools"/"score_predictionsgt_action_chunk_bank.py"),"--predictionsgt-pkl",str(PKL),"--frame-root",str(FR),"--homography-cache",str(H),"--sequence-fps-json",str(FPS),"--compact-model-output"]
 execute("score_forward",1,common+["--out-jsonl",str(f),"--out-summary",str(OUT/"forward_summary.json")]);execute("score_backward",2,common+["--reverse","--out-jsonl",str(b),"--out-summary",str(OUT/"backward_summary.json")]);execute("score_neighbors",3,[sys.executable,str(REPO/"tools"/"score_action_chunk_neighbor_bank.py"),"--predictionsgt-pkl",str(PKL),"--homography-cache",str(H),"--sequence-fps-json",str(FPS),"--seconds",".25,1,3","--bidirectional","--out-jsonl",str(n),"--out-summary",str(OUT/"neighbor_summary.json")]);execute("apply_frozen_models",4,[sys.executable,str(REPO/"tools"/"predict_action_chunk_pretrained_ensembles.py"),"--predictionsgt-pkl",str(PKL),"--forward-jsonl",str(f),"--backward-jsonl",str(b),"--neighbor-jsonl",str(n),"--base-model-dir",str(BM),"--expert-model-dir",str(EM),"--out-base-jsonl",str(bs),"--out-expert-jsonl",str(es),"--out-summary",str(OUT/"frozen_models.json")]);execute("evaluate_fixed_v53",5,[sys.executable,str(REPO/"tools"/"sweep_action_chunk_temporal_multiplicity.py"),"--tvd-root",r"D:\urap_modal_stage\TransVisDrone","--predictionsgt-pkl",str(PKL),"--base-jsonl",str(bs),"--base-field","action_chunk_neighbor_score","--expert-jsonl",str(es),"--expert-field","action_chunk_multi_expert_score","--sequence-fps-json",str(FPS),"--fixed-config-json",str(CFG),"--out-json",str(OUT/"action_bank_fixed_v53.json")]);base=json.loads(BASELINE.read_text());act=json.loads((OUT/"action_bank_fixed_v53.json").read_text())["best"];summary={"protocol":"ARD100 YOLOMG detector; frozen NPS V46/V52/V53; no ARD100 Action Bank tuning","detector_baseline":base,"action_bank":act,"gain_points":100*(act["map50"]-base["map50"])};(OUT/"action_bank_summary.json").write_text(json.dumps(summary,indent=2));report("done",6,summary=summary);return 0
if __name__=="__main__":raise SystemExit(main())
