from __future__ import annotations
import json,subprocess,sys,time
from datetime import datetime
from pathlib import Path
REPO=Path(r'C:\Users\aaron\Desktop\URAP');RUN=REPO/'artifacts'/'detached_action_chunk_multi_expert_v52';PROGRESS=RUN/'progress.json';OUT=Path(r'D:\URAP_vatd_rank_results\action_chunk_multi_expert_v52');DATA=Path(r'D:\URAP_vatd_rank_results\action_chunk_full_dev_v36');NEIGHBOR=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_v44');BASE=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_model_v46');PREREQ=Path(r'D:\URAP_vatd_rank_results\action_chunk_candidate_context_v51\official_summary.json')
def report(stage,done,total=3,**extra):
 payload={'stage':stage,'done':done,'total':total,'updated':datetime.now().astimezone().isoformat(),**extra};PROGRESS.parent.mkdir(parents=True,exist_ok=True);PROGRESS.write_text(json.dumps(payload),encoding='utf8')
def execute(stage,done,command):
 process=subprocess.Popen(command);report(stage,done,child_pid=process.pid,command=command);code=process.wait()
 if code:raise RuntimeError(f'{stage} failed with {code}')
def main():
 while not PREREQ.exists():report('waiting_for_candidate_context',0,prerequisite=str(PREREQ));time.sleep(30)
 OUT.mkdir(parents=True,exist_ok=True)
 execute('train_multi_target_expert',0,[sys.executable,str(REPO/'tools'/'train_action_chunk_multi_expert.py'),'--train-pkl',r'D:\URAP_nps_train_tvd\runs\nps_train_rank_source\predictionsgt\predictionsgt_split_0.pkl','--train-forward',str(DATA/'train_forward.jsonl'),'--train-backward',str(DATA/'train_backward.jsonl'),'--train-neighbor',str(NEIGHBOR/'train_neighbor_scores.jsonl'),'--val-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--val-forward',str(DATA/'val_forward.jsonl'),'--val-backward',str(DATA/'val_backward.jsonl'),'--val-neighbor',str(NEIGHBOR/'val_neighbor_scores.jsonl'),'--test-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--test-forward',str(DATA/'test_forward.jsonl'),'--test-backward',str(DATA/'test_backward.jsonl'),'--test-neighbor',str(NEIGHBOR/'test_neighbor_scores.jsonl'),'--out-val-scores',str(OUT/'val_expert_scores.jsonl'),'--out-test-scores',str(OUT/'test_expert_scores.jsonl'),'--out-model-dir',str(OUT/'models'),'--out-summary',str(OUT/'train_summary.json')])
 execute('select_multiplicity_gate_on_oof',1,[sys.executable,str(REPO/'tools'/'sweep_action_chunk_multiplicity_expert.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--base-jsonl',str(BASE/'val_oof_scores.jsonl'),'--base-field','action_chunk_neighbor_score','--expert-jsonl',str(OUT/'val_expert_scores.jsonl'),'--expert-field','action_chunk_multi_expert_score','--out-json',str(OUT/'val_sweep.json')])
 execute('fixed_test',2,[sys.executable,str(REPO/'tools'/'sweep_action_chunk_multiplicity_expert.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--base-jsonl',str(BASE/'test_scores.jsonl'),'--base-field','action_chunk_neighbor_score','--expert-jsonl',str(OUT/'test_expert_scores.jsonl'),'--expert-field','action_chunk_multi_expert_score','--fixed-config-json',str(OUT/'val_sweep.json'),'--out-json',str(OUT/'test_fixed.json')]);validation=json.loads((OUT/'val_sweep.json').read_text(encoding='utf8'))['best'];test=json.loads((OUT/'test_fixed.json').read_text(encoding='utf8'))['best'];summary={'protocol':'pure Action Chunk Bank multi-target specialist with label-free candidate-cluster gate; strict OOF selection; fixed test','validation_selection':validation,'test_fixed':test,'target_map50':.97,'target_met':test['map50']>=.97};(OUT/'official_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8');report('done',3,summary=summary);return 0
if __name__=='__main__':raise SystemExit(main())
