from __future__ import annotations
import json,os,subprocess,sys
from datetime import datetime
from pathlib import Path
REPO=Path(r'C:\Users\aaron\Desktop\URAP');RUN=REPO/'artifacts'/'detached_action_chunk_frame_calibration_v78';PROGRESS=RUN/'progress.json';OUT=Path(r'D:\URAP_vatd_rank_results\action_chunk_frame_calibration_v78');SOURCE=Path(r'D:\URAP_vatd_rank_results\action_chunk_future_reliability_v77');V46=Path(r'D:\URAP_vatd_rank_results\action_chunk_neighbor_model_v46');FIELDS=('action_chunk_future_rank','action_chunk_future_frame_z')
def report(stage,done,total=5,**extra):RUN.mkdir(parents=True,exist_ok=True);payload={'stage':stage,'done':done,'total':total,'updated':datetime.now().astimezone().isoformat(),**extra};PROGRESS.write_text(json.dumps(payload),encoding='utf8');print(json.dumps(payload),flush=True)
def execute(stage,done,command):
 process=subprocess.Popen(command,cwd=REPO,env={**os.environ,'PYTHONPATH':str(REPO)+os.pathsep+str(REPO/'tools'),'PYTHONUNBUFFERED':'1'});report(stage,done,child_pid=process.pid,command=command);code=process.wait()
 if code:raise RuntimeError(f'{stage} failed with {code}')
def main():
 OUT.mkdir(parents=True,exist_ok=True);tool=REPO/'tools'/'calibrate_action_chunk_frame_reliability.py';execute('calibrate_val',0,[sys.executable,str(tool),'--input-jsonl',str(SOURCE/'val_oof_scores.jsonl'),'--input-field','action_chunk_future_reliability','--output-jsonl',str(OUT/'val_scores.jsonl')]);execute('calibrate_test',1,[sys.executable,str(tool),'--input-jsonl',str(SOURCE/'test_scores.jsonl'),'--input-field','action_chunk_future_reliability','--output-jsonl',str(OUT/'test_scores.jsonl')]);weights='0 .005 .01 .02 .04 .06 .08 .1 .14 .2 .3 .4';best=None
 for offset,field in enumerate(FIELDS):
  path=OUT/f'val_{field}.json';execute(f'validate_{field}',2+offset,[sys.executable,str(REPO/'tools'/'sweep_action_chunk_two_row_ensemble.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--score-a',str(V46/'val_oof_scores.jsonl'),'--field-a','action_chunk_neighbor_score','--score-b',str(OUT/'val_scores.jsonl'),'--field-b',field,'--alphas',weights,'--betas',weights,'--out-json',str(path)]);candidate={**json.loads(path.read_text(encoding='utf8'))['best'],'field':field};best=candidate if best is None or candidate['map50']>best['map50'] else best
 (OUT/'validation_selection.json').write_text(json.dumps(best,indent=2),encoding='utf8');execute('fixed_test',4,[sys.executable,str(REPO/'tools'/'sweep_action_chunk_two_row_ensemble.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--score-a',str(V46/'test_scores.jsonl'),'--field-a','action_chunk_neighbor_score','--score-b',str(OUT/'test_scores.jsonl'),'--field-b',best['field'],'--alphas',str(best['alpha']),'--betas',str(best['beta']),'--out-json',str(OUT/'test_fixed.json')]);test=json.loads((OUT/'test_fixed.json').read_text(encoding='utf8'))['best'];summary={'protocol':'pure Action Chunk future reliability with per-frame distribution-free calibration; OOF selection; fixed test','validation_selection':best,'test_fixed':test,'target_map50':.97,'target_met':test['map50']>=.97};(OUT/'official_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8');report('done',5,summary=summary);return 0
if __name__=='__main__':raise SystemExit(main())
