from __future__ import annotations
import json,os,subprocess,sys,time
from datetime import datetime,timezone
from pathlib import Path
REPO=Path(r'C:\Users\aaron\Desktop\URAP');PYTHON=Path(sys.executable);RUN=REPO/'artifacts'/'detached_action_chunk_graph_v43';PROGRESS=RUN/'progress.json';OUT=Path(r'D:\URAP_vatd_rank_results\action_chunk_graph_v43');GEOM=Path(r'D:\URAP_vatd_rank_results\action_chunk_geometry_v40');HOM=Path(r'D:\URAP_vatd_rank_results\nps_action_bank_cmc_v2\homographies');PREREQ=Path(r'D:\URAP_vatd_rank_results\action_chunk_pairwise_v41\official_summary.json')
def report(stage,done,**extra):
 RUN.mkdir(parents=True,exist_ok=True);payload={'stage':stage,'done':done,'total':4,'updated':datetime.now(timezone.utc).astimezone().isoformat(),**extra};PROGRESS.write_text(json.dumps(payload,indent=2),encoding='utf8');print(json.dumps(payload),flush=True)
def execute(stage,done,cmd):
 process=subprocess.Popen(cmd,cwd=REPO,env={**os.environ,'PYTHONPATH':str(REPO)+os.pathsep+str(REPO/'tools'),'PYTHONUNBUFFERED':'1'});report(stage,done,child_pid=process.pid,command=cmd);code=process.wait()
 if code:raise subprocess.CalledProcessError(code,cmd)
def main():
 OUT.mkdir(parents=True,exist_ok=True)
 while not PREREQ.is_file():report('waiting_for_pairwise_audit',0,prerequisite=str(PREREQ));time.sleep(30)
 execute('score_validation_graph',0,[str(PYTHON),str(REPO/'tools'/'score_action_chunk_graph.py'),'--predictionsgt-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--unary-scores',str(GEOM/'val_oof_scores.jsonl'),'--unary-field','action_chunk_geometry_score','--homography-cache',str(HOM/'val.pkl'),'--out-jsonl',str(OUT/'val_graph_scores.jsonl'),'--out-summary',str(OUT/'val_graph_summary.json')]);fields=json.loads((OUT/'val_graph_summary.json').read_text(encoding='utf8'))['fields'];best=None
 for index,field in enumerate(fields):
  path=OUT/f'val_sweep_{field}.json';execute(f'validate_{field}',1,[str(PYTHON),str(REPO/'tools'/'sweep_tvd_predictionsgt_score_fusion.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_nps_val_tvd\runs\nps_val_rank_source\predictionsgt\predictionsgt_split_0_official_labels.pkl','--tracklet-jsonl',str(OUT/'val_graph_scores.jsonl'),'--per-row-score','--score-field',field,'--modes','geom-mix','--alphas','.02,.04,.06,.08,.1,.14,.2,.3,.4,.55','--out-json',str(path)]);candidate=json.loads(path.read_text(encoding='utf8'))['best']|{'field':field}
  if best is None or candidate['map50']>best['map50']:best=candidate
 (OUT/'validation_selection.json').write_text(json.dumps(best,indent=2),encoding='utf8');execute('score_test_graph',2,[str(PYTHON),str(REPO/'tools'/'score_action_chunk_graph.py'),'--predictionsgt-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--unary-scores',str(GEOM/'test_scores.jsonl'),'--unary-field','action_chunk_geometry_score','--homography-cache',str(HOM/'test.pkl'),'--out-jsonl',str(OUT/'test_graph_scores.jsonl'),'--out-summary',str(OUT/'test_graph_summary.json')]);execute('fixed_test',3,[str(PYTHON),str(REPO/'tools'/'sweep_tvd_predictionsgt_score_fusion.py'),'--tvd-root',r'D:\urap_modal_stage\TransVisDrone','--predictionsgt-pkl',r'D:\URAP_vatd_rank_inputs\nps_predictionsgt_split_0.pkl','--tracklet-jsonl',str(OUT/'test_graph_scores.jsonl'),'--per-row-score','--score-field',best['field'],'--modes','geom-mix','--alphas',str(best['alpha']),'--out-json',str(OUT/'test_fixed.json')]);test=json.loads((OUT/'test_fixed.json').read_text(encoding='utf8'))['best'];summary={'protocol':'pure bidirectional Action Chunk candidate graph; strict OOF field and fusion selection; fixed Clips41-50 test','validation_selection':best,'test_fixed':test,'target_map50':.97,'target_met':test['map50']>=.97};(OUT/'official_summary.json').write_text(json.dumps(summary,indent=2),encoding='utf8');report('done',4,summary=summary);return 0
if __name__=='__main__':raise SystemExit(main())
